# Generated by Django 5.2 on 2025-08-01 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0005_videotemplates_doctor_employee_doctor_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecontent',
            name='employee',
        ),
        migrations.AddField(
            model_name='imagecontent',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='image_contents', to='employee_app.doctorvideo'),
            preserve_default=False,
        ),
    ]
