# Generated by Django 5.2 on 2025-08-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0006_remove_imagecontent_employee_imagecontent_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotemplates',
            name='custom_text',
            field=models.TextField(blank=True, help_text="Template's default text like 'Good Morning'", null=True),
        ),
    ]
