# Generated by Django 5.2.6 on 2025-09-08 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0008_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateBrandPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.brand')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.videotemplates')),
            ],
            options={
                'unique_together': {('template', 'brand')},
            },
        ),
        migrations.AddField(
            model_name='videotemplates',
            name='selected_brands',
            field=models.ManyToManyField(blank=True, help_text='Brands associated with this template and their positions', related_name='templates', through='employee_app.TemplateBrandPosition', to='employee_app.brand'),
        ),
    ]
