# Generated by Django 5.2.6 on 2025-09-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0009_templatebrandposition_videotemplates_selected_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatebrandposition',
            name='height',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='templatebrandposition',
            name='width',
            field=models.IntegerField(default=100),
        ),
    ]
