# Generated by Django 5.2 on 2025-09-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0010_templatebrandposition_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videotemplates',
            name='selected_brands',
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.CharField(choices=[('PAIN', 'Pain'), ('STROKE_PREVENTION', 'In Prevention of Stroke'), ('NEURO_PROTECTORS', 'Neuro-Protectors'), ('MIGRAINE_VERTIGO', 'Migraine & Vertigo'), ('ANTI_PSYCHOTICS', 'Anti-Psychotics'), ('ANTI_DEPRESSANT', 'Anti-Depressant'), ('ANTI_EPILEPTIC', 'Anti-Epileptic'), ('SEDATIVES', 'Sedatives / Anti Anxiolytics')], default='PAIN', max_length=50),
        ),
        migrations.AddField(
            model_name='videotemplates',
            name='brand_area_settings',
            field=models.JSONField(blank=True, help_text="Brand placement area: {'enabled': True, 'x': 50, 'y': 400, 'width': 700, 'height': 150, 'brandWidth': 100, 'brandHeight': 60}", null=True),
        ),
        migrations.DeleteModel(
            name='TemplateBrandPosition',
        ),
    ]
