# Generated by Django 5.2 on 2025-09-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0011_remove_videotemplates_selected_brands_brand_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorvideo',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorvideo',
            name='mobile_number',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='doctorvideo',
            name='name',
            field=models.CharField(db_index=True, max_length=285),
        ),
        migrations.AlterField(
            model_name='doctorvideo',
            name='specialization',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AddIndex(
            model_name='doctorvideo',
            index=models.Index(fields=['employee', 'created_at'], name='employee_ap_employe_9aeb20_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorvideo',
            index=models.Index(fields=['mobile_number', 'name'], name='employee_ap_mobile__c48836_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorvideo',
            index=models.Index(fields=['specialization', 'city'], name='employee_ap_special_7b3d88_idx'),
        ),
    ]
