# Generated by Django 5.2 on 2025-09-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0013_fix_duplicate_mobiles'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='doctorvideo',
            index=models.Index(fields=['created_at', 'employee'], name='employee_ap_created_a53551_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorvideo',
            index=models.Index(fields=['name', 'specialization'], name='employee_ap_name_06d05c_idx'),
        ),
    ]
