# Generated by Django 5.2 on 2025-09-14 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0014_doctorvideo_employee_ap_created_a53551_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoroutputvideo',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_videos', to='employee_app.doctorvideo'),
        ),
    ]
