# Generated by Django 5.2 on 2025-09-14 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0015_alter_doctoroutputvideo_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotemplates',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to='employee_app.employee'),
        ),
        migrations.AddField(
            model_name='videotemplates',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
