# Generated by Django 5.2 on 2025-09-14 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0016_videotemplates_created_by_videotemplates_is_public'),
        ('employee_app', '0017_add_existing_template_fields'),
    ]

    operations = [
    ]
