# Generated by Django 5.2 on 2025-09-17 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0018_merge_20250914_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoroutputvideo',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='doctoroutputvideo',
            name='template',
        ),
        migrations.CreateModel(
            name='DoctorUsageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.CharField(default='image', max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_history', to='employee_app.doctorvideo')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.employee')),
                ('image_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_app.imagecontent')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.videotemplates')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='DoctorOutputVideo',
        ),
    ]
