# Generated by Django 5.2 on 2025-09-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0019_remove_doctoroutputvideo_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorvideo',
            name='mobile_number',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='doctorvideo',
            unique_together={('employee', 'mobile_number')},
        ),
    ]
