# Generated by Django 5.2 on 2025-09-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0020_alter_doctorvideo_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='rbm_region',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('rbm_region', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['login_code', 'rbm_region'], name='employee_ap_login_c_cdcf92_idx'), models.Index(fields=['rbm_region'], name='employee_ap_rbm_reg_e43798_idx')],
            },
        ),
    ]
