# Generated by Django 5.2 on 2025-09-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0021_employee_designation_employee_rbm_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeloginhistory',
            name='employee_identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
